services:
  - type: web
    name: WhatsBixby
    env: node      
    branch: master
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
