services:
  - type: web
    name: WhatsBixby
    env: node
    branch: master
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
